---
- name: Déployer et configurer GLPI
  hosts: web
  become: yes
  vars_files:
    - vault.yaml

  tasks:
    - name: Installer les paquets requis
      apt:
        name:
          - apache2
          - php
          - php8.2-fpm
          - mariadb-server
          - mariadb-client
          - python3-pymysql
          - php-xml
          - php-common
          - php-json
          - php-mysql
          - php-mbstring
          - php-curl
          - php-gd
          - php-intl
          - php-zip
          - php-bz2
          - php-imap
          - php-apcu
          - php-ldap
        state: present
        update_cache: yes

    - name: Vérifier si MariaDB utilise unix_socket
      ansible.builtin.command: "mysql -u root -e \"SELECT plugin FROM mysql.user WHERE User='root';\""
      register: mariadb_auth
      changed_when: false
      failed_when: mariadb_auth.rc != 0 and 'Access denied' not in mariadb_auth.stderr
